### ISSUE TITLE
The bot does not join the voice

### ISSUE THREAD

**Issue by Falkys** [larsrickert/discord-player-plus#29]
### Describe the bug
```
const player = client.player.get(message.guild.id)

const searchResult = await player.search("Metamorphosis");

if (searchResult?.tracks.length) {

  await player.play({

    channel: channel,

    tracks: searchResult.tracks[0],

  });

}
```
### Reproduction

I run the code and the bot says that everything is fine, although it doesn’t log into voice and doesn’t write anything to the console. Adms perms he has

### System Info

```shell
Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    discord-player-plus: ^2.0.5 => 2.0.5
    discord.js: ^14.14.1 => 14.14.1
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/larsrickert/discord-player-plus/issues) that reports the same bug to avoid creating a duplicate.

**Comment by larsrickert** [comment]
Hey, the player does not log errors directly. Can you please add an error listener and check if there are any errors emitted?

You can add player listeners like so:

```ts
player.addListener("error", (error) => {
  console.log("Player error", error);
});
```

**Comment by Falkys** [comment]
> Hey, the player does not log errors directly. Can you please add an error listener and check if there are any errors emitted?
> 
> You can add player listeners like so (or [see docs](https://discordplayerplus.lars-rickert.de/api/events.html)):
> 
> ```ts
> player.on("error", (error) => {
>   console.log("Player error", error);
> });
> ```
> 
> Using the [pre-build play command](https://discordplayerplus.lars-rickert.de/guide/commands.html) works fine for me
error listener did not detect any errors and the commands do not work, it says the app is not responding

**Comment by larsrickert** [comment]
> error listener did not detect any errors and the commands do not work, slashs are not added

When not even the slash commands are added then thats a sign that your bot does not connect to discord at all. Is it shown as online?

If yes, can you please change to code to the following and provide me the console output?

```ts
console.log("DEBUG 1");

const player = client.player.get(message.guild.id);

console.log("DEBUG 2");

player.on("error", (error) => {
  console.log("Player error", error);
});

const searchResult = await player.search("Metamorphosis");

console.log("DEBUG 3", searchResult);

if (searchResult?.tracks.length) {
  await player.play({
    channel: channel,
    tracks: searchResult.tracks[0],
  });
}

console.log("DEBUG 4");
