### ISSUE TITLE
Youtube playlist search

### ISSUE THREAD

**Issue by LuciaDX** [larsrickert/discord-player-plus#5]
### Describe the bug

If you search youtube playlist that starts with https://www.youtube.com/playlist?... it wont count as playlist
+ play-dl cant search by links you need to pass playlist id instead of full link
+ by searching playlist with playdl.search() it cant get all videos in it but it works with playdl.playlist_info()

### Reproduction

Try to add youtube playlist

### System Info

```shell
Binaries:
    Node: 18.7.0 - /usr/bin/node
    npm: 8.15.0 - /usr/bin/npm
  npmPackages:
    discord-player-plus: ^1.1.1 => 1.1.1
    discord.js: ^14.0.3 => 14.0.3
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/larsrickert/discord-player-plus/issues) that reports the same bug to avoid creating a duplicate.

**Comment by larsrickert** [comment]
Hey, thanks for reporting the issue! Its now fixed. It can now search playlist that starts with `https://www.youtube.com/watch` and `https://www.youtube.com/playlist`.

Regarding the number of tracks, note the following: YouTube handles /watch and /playlist links a little bit different, e.g.
- https://www.youtube.com/watch?v=89S-RbszwJE&list=PLMC9KNkIncKseYxDN2niH6glGRWKsLtde
- https://www.youtube.com/playlist?list=PLMC9KNkIncKseYxDN2niH6glGRWKsLtde

Both playlist are the same but the second one (`/playlist`) contains all 236 songs while the first one (`/watch`) only shows 200 by default. If you click on the last song, it will show the remaining songs and the link changes. If you use the updated link when searching with `discord-player-plus` all songs will the provided. If using the initial `/watch` link, you will only get 200 songs like on YouTube
